### ISSUE TITLE
"Page Closed" Error message

### ISSUE THREAD

**Issue by zleung9** [PathOnAI/LiteWebAgent#104]
A similar error messages with FunctionCallingAgent `python -m function_calling_main --agent_type FunctionCallingAgent --starting_url https://www.google.com --goal 'search dining table' --plan 'search dining table' --log_folder log`
post here in case it is related to #103

System: Mac OS Sequoia 15.0

```
/Users/zhuliang/miniconda3/envs/agent/lib/python3.10/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'smart_union' has been removed
  warnings.warn(message, UserWarning)
Registering tool: navigation
Registering tool: select_option
Registering tool: upload_file
Registering tool: webscraping
Traceback (most recent call last):
  File "/Users/zhuliang/miniconda3/envs/agent/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/zhuliang/miniconda3/envs/agent/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/zhuliang/LiteWebAgent/function_calling_main.py", line 45, in <module>
    main(args)
  File "/Users/zhuliang/LiteWebAgent/function_calling_main.py", line 15, in main
    agent = setup_function_calling_web_agent(args.starting_url, args.goal, model_name=args.model, agent_type=args.agent_type,
  File "/Users/zhuliang/LiteWebAgent/litewebagent/core/agent_factory.py", line 73, in setup_function_calling_web_agent
    page.goto(starting_url)
  File "/Users/zhuliang/miniconda3/envs/agent/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 9303, in goto
    self._sync(
  File "/Users/zhuliang/miniconda3/envs/agent/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
  File "/Users/zhuliang/miniconda3/envs/agent/lib/python3.10/site-packages/playwright/_impl/_page.py", line 473, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/Users/zhuliang/miniconda3/envs/agent/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 138, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/Users/zhuliang/miniconda3/envs/agent/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/Users/zhuliang/miniconda3/envs/agent/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 490, in wrap_api_call
    return await cb()
  File "/Users/zhuliang/miniconda3/envs/agent/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 99, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Page closed
=========================== logs ===========================
navigating to "https://www.google.com/", waiting until "load"
============================================================
```

**Comment by Tata0703** [comment]
Was any chromium browser opened in this case?

**Comment by Tata0703** [comment]
<img width="1646" alt="image" src="https://github.com/user-attachments/assets/35626b60-d50e-43e9-bf4e-57ed7318807f">
if you add import pdb; pdb.set_trace(), before line 'page.goto(starting_url)' of the core/agent_factory.py file, are you able to see this screenshot?

**Comment by danni-z-loggia** [comment]
Since you mentioned that it worked once, the issue is likely due to a timeout. Some pages take longer to load, causing Playwright to close them if they exceed the default 30-second timeout. We can extend this to 60 seconds by passing a timeout option to the goto() method. You can find the relevant code here: https://github.com/PathOnAI/LiteWebAgent/blob/main/litewebagent/core/agent_factory.py#L74

**Comment by Tata0703** [comment]
Since you mentioned that it worked once, the issue is likely due to a timeout. Some pages take longer to load, causing Playwright to close them if they exceed the default 30-second timeout. We can extend this to 60 seconds by passing a timeout option to the goto() method. You can find the relevant code here: https://github.com/PathOnAI/LiteWebAgent/blob/main/litewebagent/core/agent_factory.py#L74
