### ISSUE TITLE
fix error 2: locate element

### ISSUE THREAD

**Issue by danni-z-loggia** [PathOnAI/LiteWebAgent#118]
```
['To add a bag of dog food to the cart, click on the "Add to cart" button for the "Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag."\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, click on the "Add to cart" button next to the first product.\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, I will click on the "Add to cart" button for the "Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag (Pack of 1)" product.\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, I\'ll click on the "Add to cart" button for the "Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag (Pack of 1)".\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, you should click on the "Add to cart" button for the "Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag".\n\n```click(\'741\')```', 'To add the "Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag" to the cart, click the "Add to cart" button.\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, I need to click on the "Add to cart" button for a specific product.\n\n```click(\'741\')```', 'To add the Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag to the cart, click the "Add to cart" button for that item.\n\n```click(\'741\')```', 'To add the "Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag" to the cart, click the "Add to cart" button associated with it.\n\n```click(\'741\')```', 'To add the first bag of dog food to the cart, click on the "Add to cart" button for the Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag.\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, I need to click the "Add to cart" button for a specific product. I\'ll select the first dog food product shown in the results.\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, I need to click on the "Add to cart" button for the desired product. I\'ll choose the first listing.\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, click the "Add to cart" button for the "Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag (Pack of 1)".\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, I need to click the "Add to cart" button for the Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag.\n\n```click(\'741\')```', 'To accomplish the goal of adding a bag of dog food to the cart, I need to click the "Add to cart" button for the first visible product.\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, click the "Add to cart" button for the first product, the "Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag."\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, click the "Add to cart" button next to the "Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag (Pack of 1)".\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, click the "Add to cart" button next to the "Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag."\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, I\'ll click on the "Add to cart" button for the first product displayed.\n\n```click(\'741\')```', 'To add a bag of dog food to the cart, click on the "Add to cart" button next to the "Amazon Brand – Wag Dry Dog Food, Beef and Brown Rice, 30 lb Bag (Pack of 1)".\n\n```click(\'741\')```']
defaultdict(<class 'int'>, {"click('741')": 20})
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/danqingzhang/Desktop/LiteWebAgent/prompting_main.py", line 44, in <module>
    main(args)
  File "/Users/danqingzhang/Desktop/LiteWebAgent/prompting_main.py", line 19, in main
    response = agent.send_prompt(args.plan)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danqingzhang/Desktop/LiteWebAgent/litewebagent/agents/PromptAgents/PromptAgent.py", line 21, in send_prompt
    trajectory = self.send_completion_request(plan, 0, [])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danqingzhang/Desktop/LiteWebAgent/litewebagent/agents/PromptAgents/PromptAgent.py", line 84, in send_completion_request
    return self.send_completion_request(plan, depth + 1, trajectory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danqingzhang/Desktop/LiteWebAgent/litewebagent/agents/PromptAgents/PromptAgent.py", line 84, in send_completion_request
    return self.send_completion_request(plan, depth + 1, trajectory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danqingzhang/Desktop/LiteWebAgent/litewebagent/agents/PromptAgents/PromptAgent.py", line 84, in send_completion_request
    return self.send_completion_request(plan, depth + 1, trajectory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 1 more time]
  File "/Users/danqingzhang/Desktop/LiteWebAgent/litewebagent/agents/PromptAgents/PromptAgent.py", line 65, in send_completion_request
    execute_action(next_action, self.action_set, page, context, self.goal, page_info['interactive_elements'],
  File "/Users/danqingzhang/Desktop/LiteWebAgent/litewebagent/action/utils.py", line 19, in execute_action
    result = locate_element(page, extracted_number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danqingzhang/Desktop/LiteWebAgent/litewebagent/utils/utils.py", line 83, in locate_element
    elements = page.query_selector_all(combined_selector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danqingzhang/Desktop/LiteWebAgent/venv/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 8237, in query_selector_all
    self._sync(self._impl_obj.query_selector_all(selector=selector))
  File "/Users/danqingzhang/Desktop/LiteWebAgent/venv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/Users/danqingzhang/Desktop/LiteWebAgent/venv/lib/python3.11/site-packages/playwright/_impl/_page.py", line 337, in query_selector_all
    return await self._main_frame.query_selector_all(selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danqingzhang/Desktop/LiteWebAgent/venv/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 301, in query_selector_all
    return list(
           ^^^^^
  File "/Users/danqingzhang/Desktop/LiteWebAgent/venv/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 509, in from_channel
    return channel._object
           ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute '_object'
(venv) danqingzhang@Danqings-MBP LiteWebAgent % node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v18.18.0
```

**Comment by TataKKKL** [comment]
https://github.com/PathOnAI/LiteWebAgent/pull/120
